<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-6UHVP5N" name="com.api.service.CITIBANK_LOP_SG" tests="10" failures="0" timestamp="2020-07-07T19:41:28 IST" time="73.135" errors="2">
  <testcase name="Initiate_the_cardAuth_authorize_API_with_valid_fields_and_verify_the_Expected_Result" time="6.561" classname="com.api.service.CITIBANK_LOP_SG"/>
  <system-out/>
  <testcase name="Initiate_the_cardAuth_access_API_with_valid_fields_and_verify_the_Expected_Result" time="3.433" classname="com.api.service.CITIBANK_LOP_SG"/>
  <system-out/>
  <testcase name="Initiate_the_loan_eligibility_API_with_valid_fields_and_verify_the_Expected_Result" time="4.229" classname="com.api.service.CITIBANK_LOP_SG"/>
  <system-out/>
  <testcase name="Initiate_the_Loan_RePYMENT_API_with_valid_fields_and_verify_the_Expected_Result" time="7.360" classname="com.api.service.CITIBANK_LOP_SG"/>
  <system-out/>
  <testcase name="Initiate_the_LoanBooking_API_with_valid_fields_and_verify_the_Expected_Result" time="7.624" classname="com.api.service.CITIBANK_LOP_SG"/>
  <system-out/>
  <testcase name="Initiate_the_E2EKEY_API_with_valid_fields_and_verify_the_Expected_Result" time="10.645" classname="com.api.service.CITIBANK_LOP_SG"/>
  <system-out/>
  <testcase name="Initiate_the_ValidateOTP_API_with_valid_fields_and_verify_the_Expected_Result" time="9.048" classname="com.api.service.CITIBANK_LOP_SG"/>
  <system-out/>
  <testcase name="Initiate_the_LoanBooking_Confirmation_API_with_valid_fields_and_verify_the_Expected_Result" time="22.468" classname="com.api.service.CITIBANK_LOP_SG"/>
  <system-out/>
  <testcase name="To_verify_the_request_with_invalid_client_id_and_Authorization" time="1.035" classname="com.api.service.CITIBANK_LOP_SG">
    <error type="com.jayway.jsonpath.PathNotFoundException" message="Missing property in path $[&#039;moreInfo&#039;]">
      <![CDATA[com.jayway.jsonpath.PathNotFoundException: Missing property in path $['moreInfo']
at com.jayway.jsonpath.internal.path.PathToken.handleObjectProperty(PathToken.java:72)
at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:79)
at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:53)
at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:61)
at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:102)
at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:85)
at com.api.service.LOP_Source.Card_Authentication(LOP_Source.java:56)
at com.api.service.CITIBANK_LOP_SG.To_verify_the_request_with_invalid_client_id_and_Authorization(CITIBANK_LOP_SG.java:117)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- To_verify_the_request_with_invalid_client_id_and_Authorization -->
  <system-out/>
  <testcase name="To_verify_the_request_with_invalid_accountId" time="0.732" classname="com.api.service.CITIBANK_LOP_SG">
    <error type="com.jayway.jsonpath.PathNotFoundException" message="Missing property in path $[&#039;moreInfo&#039;]">
      <![CDATA[com.jayway.jsonpath.PathNotFoundException: Missing property in path $['moreInfo']
at com.jayway.jsonpath.internal.path.PathToken.handleObjectProperty(PathToken.java:72)
at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:79)
at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:53)
at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:61)
at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:102)
at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:85)
at com.api.service.LOP_Source.Card_Authentication(LOP_Source.java:56)
at com.api.service.CITIBANK_LOP_SG.To_verify_the_request_with_invalid_accountId(CITIBANK_LOP_SG.java:135)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- To_verify_the_request_with_invalid_accountId -->
  <system-out/>
</testsuite> <!-- com.api.service.CITIBANK_LOP_SG -->
